### ISSUE TITLE
How to train or predict 12-leads ECG data?

### ISSUE THREAD

**Issue by 66Kevin** [ChristophReich1996/ECG_Classification#2]
Hi,
Thanks for your code. I would like to ask how to train your network on 12-leads ECG data? just change the dimension of input?

**Comment by ChristophReich1996** [comment]
Hi @66Kevin,

Thanks for your interest :) Yes, very broadly, simply change the input dimensions. In the case of the spectrogram, this is pretty sight forward, simply compute the spectrogram for each lead. This should result in an input tensor to the spectrogram encoder of the shape `[batch size, leads, h, w]`. To adapt the network simply change the number of input channels in [config.py](https://github.com/ChristophReich1996/ECG_Classification/blob/main/ecg_classification/config.py) (`"spectrogram_encoder_channels"`). In the case of the input to the signal encoder (Transformer encoder for ++ version), this gets a bit tricky. Currently, the transformer gets a "patched" sequence as an input (shape is [batch size, n sequences, windows size=256]). I would recommend generating a tensor of the shape `[batch size, leads, n sequences, windows size=256]`. Then you can do multiple things. The first thing which comes to my mind would be to use an FFNN to reduce the leads dimension. Another idea would be to reshape the tensor to `[batch size, n sequences, leads * windows size]` and change the feature dimension of the transformer (feature dimension may be too large... Reduce dimension again with FFNN?). Again another idea could be to encode all leads in the batch size and then pool the resulting latent vector before feeding the latent vector to the spectrogram encoder.

If you find a suitable solution for 12-lead ECG signals feel free to open a pull request with your code :)

Cheers
Christoph

**Comment by 66Kevin** [comment]
Thanks for your reply! I'll work on it :)
